export var UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export var ADD_DESTINATION = 'ADD_DESTINATION';
export var ADD_JOURNEYS = 'ADD_JOURNEYS';
export var REMOVE_JOURNEYS = 'REMOVE_JOURNEYS';
export var REMOVE_DESTINATION = 'REMOVE_DESTINATION';